name: test

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-2022
        version:
          - '2.2.6'
    steps:
      - uses: actions/checkout@v5

      - name: Set cache-key
        id: vars
        run: |
          if [[ ${{ matrix.version }} == stable ]]; then
            echo ::set-output name=cache-key::$(date +%Y-%m-%d)
          else
            echo ::set-output name=cache-key::${{ matrix.version }}
          fi
        shell: bash

      - name: Print cache-key
        run: echo cache-key = ${{ steps.vars.outputs.cache-key }}

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v4
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ steps.vars.outputs.cache-key }}
        if: runner.os != 'Windows'
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
        if: runner.os != 'Windows'
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.version }}

      - name: Test examples
        working-directory: examples
        run: |
          for file in $(ls -v example_*nim); do
            echo "=== test: $file ==="
            nim c "$file"
            echo ""
          done
        shell: bash
